sequenceDiagram
    participant SH as Source HSM
    participant S as Source Agent
    participant ST as Store
    actor CLI as Cluster CLI
    participant C as Cluster Manager
    participant D as Destination
    participant DH as Destination HSM

    CLI->>+C: Transfer<br>(Realm, Source, Destination, Range)

    C->>+D: PrepareTransfer<br>(Realm, Source, Destination, Range)
    D->>+DH: PrepareTransfer<br>(Realm, Source, Destination, Range)
    DH-->>-D: Ok (Nonce, PreparedStatement, LogEntry, Delta)
    note left of DH: LogEntry includes information about the proposed transfer.<br/>This is carried forward in subsequent log entries.
    note left of DH: The nonce is used to ensure<br>that the transferIn/Statement is current.
    D-->>D: Add To Append Queue (LogEntry, Delta)
    D-->>D: Wait For LogEntry to commit
    D-->>-C: Ok (Nonce)

    C->>+S: TransferOut (Source, Destination, Range, Nonce, PreparedStatement)
    S->>+ST: ReadLastLogEntry
    ST-->>-S: Ok (LogEntry)
    S->>+ST: ReadProof
    ST-->>-S: Ok (Proof)
    S->>+SH: TransferOut<br>(Source, Destination, Range, Proof, Nonce, PreparedStatement)
    rect rgb(223, 223, 223)
    note left of DH: Partition now unavailable until TransferIn completes

    SH-->>-S: Ok (LogEntry, Delta)
    note left of S: LogEntry includes information about the transfer partition.<br/>This is carried forward in subsequent log entries.
    S-->>S: Add To Append Queue (LogEntry, Delta)
    note left of S: Once this log entry commits the transfer cannot be undone.
    S-->>S: Wait For LogEntry to commit
    S->>+SH: TransferStatement (Source, Destination, Nonce)
    note right of SH: HSM Verifies that the log entry<br>generated by TransferOut is committed.
    SH-->>-S: Ok (TransferStatement)
    S-->>-C: Ok (Partition, TransferStatement)

    C->>+D:TransferIn<br>(Source, Destination, Partition, Nonce, TransferStatement)
    D->>+ST: ReadLastLogEntry
    ST-->>-D: Ok (LogEntry)
    D->>+ST: ReadProofs
    ST-->>-D: Ok (Proofs)
    D->>+DH: TransferIn<br>(Destination, Partition, Nonce, TransferStatement, Proofs)
    DH-->>-D: Ok (LogEntry, Delta)
    end
    note left of DH: Transferring partition info removed from LogEntry
    D-->>D: Add To Append Queue (LogEntry, Delta)
    D-->>D: Wait For LogEntry to commit
    D-->>-C: Ok ()
    
    C->>+S: CompleteTransfer (Source, Destination, Range)
    S->>+SH: CompleteTransfer<br>(Source, Destination, Range)
    SH-->>-S: Ok (LogEntry, Delta)
    note left of S: Transferring partition info removed from LogEntry
    S-->>S: Add To Append Queue (LogEntry, Delta)
    S-->>S: Wait For LogEntry to commit(?)
    S-->>-C: Ok

    C-->>-CLI: Ok
