[package]
name = "hsmcore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = "0.10.1"
bitvec = { version = "1.0.1", features = ["serde"] }
bytes = "1.4.0"
digest = "0.10.6"
hkdf = "0.12.3"
hmac = "0.12.1"
rand = "0.8.5"
rmp = "0.8.11"
rmp-serde = "1.1.1"
serde = "1.0.152"
sha2 = "0.10.6"
sharks = "0.5.0"
subtle = "2.4.1"
tracing = "0.1.37"
voprf = "0.4.0"

[dev-dependencies]
async-recursion = "1.0.2"
async-trait = "0.1.64"
tokio = { version = "1.25.0", features = ["rt-multi-thread", "macros"] }
