[package]
name = "entrust-hsm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hsmcore = { path = "../hsmcore" }

[lib]
crate-type=["staticlib"]
