[package]
name = "entrust_nfast"
version = "0.1.0"
edition = "2021"
links = "seelib"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
