[package]
name = "cluster_cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cluster"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agent_api = { path = "../agent_api" }
anyhow = { workspace = true }
clap = { workspace = true }
cli-table = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
hsmcore = { workspace = true }
juicebox_hsm = { path = ".." }
juicebox-sdk = { workspace = true }
juicebox-sdk-core = { workspace = true }
juicebox-sdk-networking = { workspace = true }
juicebox-sdk-realm-auth = { workspace = true }
observability = { path = "../observability" }
reqwest = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
expect-test = { workspace = true }
