[package]
name = "cluster_manager"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agent_api = { path = "../agent_api" }
anyhow = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
cluster_api = { path = "../cluster_api" }
cluster_core = { path = "../cluster_core" }
ctrlc = { workspace = true }
futures = { workspace = true }
google = { path = "../google" }
hsmcore = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
juicebox_hsm = { path = ".." }
juicebox-sdk-core = { workspace = true }
observability = { path = "../observability" }
opentelemetry = { workspace = true }
opentelemetry-http = { workspace = true }
juicebox-sdk-networking = { workspace = true }
store = { path = "../store" }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
url = { workspace = true }

[dev-dependencies]
expect-test = { workspace = true }
