[package]
name = "ceremony"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.6", default_features = false, features = [
    "derive",
    "help",
    "std",
    "usage",
] }
hex = "0.4.3"
sha2 = "0.10.8"
