[workspace]

members = [
    "agent_api",
    "agent_core",
    "bitvec",
    "cluster_api",
    "cluster_bench",
    "cluster_cli",
    "cluster_core",
    "cluster_manager",
    "codegen",
    "election",
    "entrust_agent",
    "entrust_api",
    "entrust_hsm",
    "entrust_init",
    "entrust_nfast",
    "google",
    "hsm_api",
    "hsm_core",
    "load_balancer",
    "lru-cache",
    "merkle_tree_docgen",
    "observability",
    "secret_manager",
    "service_core",
    "software_agent",
    "store",
    "testing",
]

default-members = [
    "agent_api",
    "agent_core",
    "bitvec",
    "cluster_api",
    "cluster_bench",
    "cluster_cli",
    "cluster_core",
    "cluster_manager",
    "codegen",
    "election",
    "google",
    "hsm_api",
    "hsm_core",
    "load_balancer",
    "lru-cache",
    "observability",
    "secret_manager",
    "service_core",
    "software_agent",
    "store",
    "testing",
]

# This allows the sdk packages to reference their workspace (for dependencies
# and such), rather than this one.
exclude = ["sdk"]
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace.dependencies]
agent_api = { path = "agent_api" }
agent_core = { path = "agent_core" }
ahash = { version = "0.8.3", default-features = false }
anyhow = "1.0.70"
async-recursion = "1.0.2"
async-trait = "0.1.64"
bitvec = { path = "bitvec" }
blake2 = { version = "0.10.6", default-features = false }
bytes = { version = "1.4.0", default-features = false }
cache = { path = "cache" }
cbor-diag = { version = "0.1.11" }
chacha20poly1305 = { version = "0.10.1", default-features = false, features = [
    "alloc",
] }
ciborium = { version = "0.2.0", default-features = false }
ciborium-io = { version = "0.2.0", default-features = false }
clap = { version = "4.3.0", features = ["derive"] }
cli-table = { version = "0.4.7", default-features = false }
cluster_api = { path = "cluster_api" }
cluster_core = { path = "cluster_core" }
criterion = "0.4.0"
ctrlc = "3.2.5"
digest = "0.10.6"
dogstatsd = "0.8.1"
election = { path = "election" }
entrust_api = { path = "entrust_api" }
entrust_nfast = { path = "entrust_nfast" }
expect-test = "1.4.1"
futures = "0.3.25"
gcp_auth = "0.8.0"
generic-array = { version = "0.14.7", features = ["serde", "zeroize"] }
google = { path = "google" }
hashbrown = { version = "0.14.0", default-features = false, features = [
    "inline-more",
    "serde",
] }
h2 = { version = "0.3.17" }
hdrhistogram = { version = "7.5.2", default-features = false }
hex = "0.4.3"
hex-literal = "0.3.4"
hkdf = "0.12.3"
hmac = "0.12.1"
hsm_api = { path = "hsm_api" }
hsm_core = { path = "hsm_core" }
http = "0.2.8"
http-body-util = "0.1.0-rc.2"
hyper = { version = "1.0.0-rc.2", features = ["http1", "http2", "server"] }
itertools = { version = "0.11" }
jsonwebtoken = { version = "8.3.0", default-features = false }
libc = { version = "0.2.139", default-features = false }
lru-cache = { path = "lru-cache" }
juicebox_sdk = { path = "sdk/rust/sdk", features = ["reqwest", "tokio"] }
juicebox_marshalling = { path = "sdk/rust/marshalling" }
juicebox_networking = { path = "sdk/rust/networking", features = [
    "distributed-tracing",
    "reqwest",
] }
juicebox_noise = { path = "sdk/rust/noise" }
juicebox_oprf = { path = "sdk/rust/oprf" }
juicebox_process_group = { path = "sdk/rust/process_group" }
juicebox_realm_api = { path = "sdk/rust/realm/api" }
juicebox_realm_auth = { path = "sdk/rust/realm/auth" }
nix = { version = "0.26.2", default-features = false, features = ["signal"] }
observability = { path = "observability" }
once_cell = "1.17.1"
opentelemetry = { version = "0.18.0", features = ["rt-tokio"] }
opentelemetry-http = "0.7.0"
opentelemetry-otlp = "0.11.0"
prost = "0.11.6"
prost-types = "0.11.6"
rand = { version = "0.8.5", default-features = false, features = ["alloc"] }
rand_core = "0.6.4"
rand_chacha = "0.3.1"
reqwest = { version = "0.11.14", default-features = false, features = [
    "rustls-tls",
] }
rustls = "0.20.8"
rustls-pemfile = "1.0"
secrecy = { version = "0.8.0", features = ["serde"] }
secret_manager = { path = "secret_manager" }
semver = "1.0.18"
serde = { version = "1.0.152", default-features = false, features = [
    "alloc",
    "derive",
] }
serde_json = "1.0.94"
service_core = { path = "service_core" }
sharks = "0.5.0"
signal-hook = "0.3.15"
spin = { version = "0.9.8", default-features = false, features = [
    "once",
    "mutex",
    "spin_mutex",
] }
store = { path = "store" }
subtle = { version = "2.4.1", default-features = false }
sysinfo = { version = "0.29" }
tempfile = "3.5.0"
thiserror = "1.0.40"
tokio = { version = "1.25.0", features = ["rt-multi-thread", "macros"] }
tokio-rustls = "0.23.4"
tonic = { version = "0.8.3", features = ["channel", "tls", "tls-webpki-roots"] }
tower = "0.4.13"
tracing = { version = "0.2.0", default-features = false, features = [
    "alloc",
    "attributes",
] }
# The latest Cargo.toml of tracing-opentelemetry in Git has an old version number.
tracing-opentelemetry = { version = "*" }
# The latest Cargo.toml of tracing-subscriber in Git has an old version number.
tracing-subscriber = { version = "*", features = ["json"] }
url = { version = "2.3.1", features = ["serde"] }
voprf = { version = "0.5.0-pre.4" }
x25519-dalek = { version = "2.0.0-rc.3", features = [
    "reusable_secrets",
    "serde",
    "static_secrets",
] }

[patch.crates-io]
gcp_auth = { git = "ssh://git@github.com/juicebox-systems/gcp_auth.git", branch = "loam-main" }
secrecy = { git = "ssh://git@github.com/juicebox-systems/secrecy.git", branch = "loam-main" }
# We need https://github.com/tokio-rs/tracing/pull/2335 to quiet down error return
# values in tokio::instrument, which is not yet unreleased.
tracing = { git = "https://github.com/tokio-rs/tracing" }
tracing-opentelemetry = { git = "https://github.com/tokio-rs/tracing" }
tracing-subscriber = { git = "https://github.com/tokio-rs/tracing" }
