[workspace]
members = ["codegen","hsmcore"]

[package]
name = "loam-mvp"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.64"
bitvec = { version = "1.0.1", features = ["serde"] }
bytes = "1.4.0"
clap = { version = "4.1.6", features = ["derive"] }
digest = "0.10.6"
futures = "0.3.25"
hmac = "0.12.1"
http = "0.2.8"
http-body-util = "0.1.0-rc.2"
hyper = { version = "1.0.0-rc.2", features = ["http1", "http2", "server"] }
prost = "0.11.6"
prost-types = "0.11.6"
rand = "0.8.5"
reqwest = { version = "0.11.14", default-features = false }
rmp = "0.8.11"
rmp-serde = "1.1.1"
serde = "1.0.152"
sha2 = "0.10.6"
sharks = "0.5.0"
tokio = { version = "1.25.0", features = ["rt-multi-thread"] }
tonic = { version = "0.8.3", features = ["channel"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
url = { version = "2.3.1", features = ["serde"] }
voprf = "0.4.0"
hsmcore = { path = "hsmcore" }


[patch.crates-io]
# waiting on this issue/pr to be resolved
# https://github.com/ferrilab/bitvec/issues/215
bitvec = { git = 'https://github.com/superfell/bitvec', branch = 'vec_order' }

[dev-dependencies]
async-recursion = "1.0.2"
criterion = "0.4.0"
hex-literal = "0.3.4"
rand_chacha = "0.3.1"

[[bench]]
name = "voprf_benchmark"
harness = false
