[workspace]
members = ["codegen","hsmcore"]

[package]
name = "loam-mvp"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace.dependencies]
aes-gcm = { version="0.10.1", default-features = false, features=["aes", "alloc"] }
async-recursion = "1.0.2"
async-trait = "0.1.64"
bitvec = { version = "1.0.1", default-features = false, features = ["alloc", "serde"] }
bytes = { version = "1.4.0", default-features = false }
ciborium = { version = "0.2.0", default-features = false }
clap = { version = "4.1.6", features = ["derive"] }
criterion = "0.4.0"
digest = "0.10.6"
futures = "0.3.25"
hex-literal = "0.3.4"
hkdf = "0.12.3"
hmac = "0.12.1"
http = "0.2.8"
http-body-util = "0.1.0-rc.2"
hyper = { version = "1.0.0-rc.2", features = ["http1", "http2", "server"] }
prost = "0.11.6"
prost-types = "0.11.6"
rand = { version = "0.8.5", default-features = false, features = ["alloc"] }
rand_chacha = "0.3.1"
reqwest = { version = "0.11.14", default-features = false }
serde = { version = "1.0.152", default-features = false, features = ["alloc", "derive"] }
sha2 = { version = "0.10.6", default-features = false }
sharks = "0.5.0"
subtle = { version = "2.4.1", default-features = false }
tokio = { version = "1.25.0", features = ["rt-multi-thread","macros"] }
tonic = { version = "0.8.3", features = ["channel"] }
tracing = { version = "0.1.37", default-features = false }
tracing-subscriber = "0.3.16"
url = { version = "2.3.1", features = ["serde"] }
voprf = "0.4.0"

[dependencies]
async-trait = { workspace = true }
bitvec = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
digest = { workspace = true }
futures = { workspace = true }
hmac = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
sharks = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }
voprf = { workspace = true }
hsmcore = { path = "hsmcore" }


[patch.crates-io]
# waiting on this issue/pr to be resolved
# https://github.com/ferrilab/bitvec/issues/215
bitvec = { git = 'https://github.com/superfell/bitvec', branch = 'vec_order' }

[dev-dependencies]
async-recursion = { workspace = true }
criterion = { workspace = true }
hex-literal = { workspace = true }
rand_chacha = { workspace = true }

[lib]
doctest = false

[[bench]]
name = "voprf_benchmark"
harness = false
