[workspace]
members = [
    "agent_core",
    "cluster_bench",
    "cluster_cli",
    "cluster_manager",
    "codegen",
    "entrust_agent",
    "entrust_api",
    "entrust_hsm",
    "entrust_init",
    "entrust_nfast",
    "hsmcore",
    "load_balancer",
    "merkle_tree_docgen",
    "software_agent",
]
default-members = [
    ".",
    "agent_core",
    "cluster_bench",
    "cluster_cli",
    "cluster_manager",
    "codegen",
    "hsmcore",
    "load_balancer",
    "software_agent",
]
# This allows the sdk packages to reference their workspace (for dependencies
# and such), rather than this one.
exclude = ["sdk"]
resolver = "2"

[package]
name = "juicebox_hsm"
version = "0.0.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace.dependencies]
ahash = { version = "0.8.3", default-features = false }
anyhow = "1.0.70"
async-recursion = "1.0.2"
async-trait = "0.1.64"
blake2 = { version = "0.10.6", default-features = false }
bytes = { version = "1.4.0", default-features = false }
cbor-diag = { version = "0.1.11" }
chacha20poly1305 = { version = "0.10.1", default-features = false, features = [
    "alloc",
] }
ciborium = { version = "0.2.0", default-features = false }
ciborium-io = { version = "0.2.0", default-features = false }
clap = { version = "4.3.0", features = ["derive"] }
cli-table = { version = "0.4.7", default-features = false }
criterion = "0.4.0"
ctrlc = "3.2.5"
digest = "0.10.6"
dogstatsd = "0.8.1"
expect-test = "1.4.1"
futures = "0.3.25"
gcp_auth = "0.8.0"
generic-array = { version = "0.14.7", features = ["serde", "zeroize"] }
hashbrown = { version = "0.14.0", default-features = false, features = [
    "inline-more",
    "serde",
] }
h2 = { version = "0.3.17" }
hdrhistogram = { version = "7.5.2", default-features = false }
hex = "0.4.3"
hex-literal = "0.3.4"
hkdf = "0.12.3"
hmac = "0.12.1"
hsmcore = { path = "hsmcore" }
http = "0.2.8"
http-body-util = "0.1.0-rc.2"
hyper = { version = "1.0.0-rc.2", features = ["http1", "http2", "server"] }
jsonwebtoken = { version = "8.3.0", default-features = false }
libc = { version = "0.2.139", default-features = false }
juicebox-sdk = { path = "sdk/rust/sdk/client", features = ["tokio"] }
juicebox-sdk-core = { path = "sdk/rust/sdk/core" }
juicebox-sdk-marshalling = { path = "sdk/rust/sdk/marshalling" }
juicebox-sdk-networking = { path = "sdk/rust/sdk/networking", features = [
    "threadsafe-futures",
    "distributed-tracing",
] }
juicebox-sdk-noise = { path = "sdk/rust/sdk/noise" }
nix = { version = "0.26.2", default-features = false, features = ["signal"] }
once_cell = "1.17.1"
opentelemetry = { version = "0.18.0", features = ["rt-tokio"] }
opentelemetry-http = "0.7.0"
opentelemetry-otlp = "0.11.0"
prost = "0.11.6"
prost-types = "0.11.6"
rand = { version = "0.8.5", default-features = false, features = ["alloc"] }
rand_core = "0.6.4"
rand_chacha = "0.3.1"
rustls = "0.20.8"
rustls-pemfile = "1.0"
reqwest = { version = "0.11.14", default-features = false, features = [
    "rustls-tls",
] }
secrecy = { version = "0.8.0", features = ["serde"] }
serde = { version = "1.0.152", default-features = false, features = [
    "alloc",
    "derive",
] }
serde_json = "1.0.94"
sharks = "0.5.0"
signal-hook = "0.3.15"
spin = { version = "0.9.8", default-features = false, features = [
    "once",
    "mutex",
    "spin_mutex",
] }
subtle = { version = "2.4.1", default-features = false }
tempfile = "3.5.0"
thiserror = "1.0.40"
tokio = { version = "1.25.0", features = ["rt-multi-thread", "macros"] }
tokio-rustls = "0.23.4"
tonic = { version = "0.8.3", features = ["channel", "tls", "tls-webpki-roots"] }
tower = "0.4.13"
tracing = { version = "0.2.0", default-features = false, features = [
    "alloc",
    "attributes",
] }
# The latest Cargo.toml of tracing-opentelemetry in Git has an old version number.
tracing-opentelemetry = { version = "*" }
# The latest Cargo.toml of tracing-subscriber in Git has an old version number.
tracing-subscriber = { version = "*", features = ["json"] }
url = { version = "2.3.1", features = ["serde"] }
voprf = { version = "0.5.0-pre.4" }
x25519-dalek = { version = "2.0.0-rc.2", features = [
    "reusable_secrets",
    "serde",
    "static_secrets",
] }

[patch.crates-io]
gcp_auth = { git = "ssh://git@github.com/juicebox-systems/gcp_auth.git", branch = "loam-main" }
secrecy = { git = "ssh://git@github.com/juicebox-systems/secrecy.git", branch = "loam-main" }
# We need https://github.com/tokio-rs/tracing/pull/2335 to quiet down error return
# values in tokio::instrument, which is not yet unreleased.
tracing = { git = "https://github.com/tokio-rs/tracing" }
tracing-opentelemetry = { git = "https://github.com/tokio-rs/tracing" }
tracing-subscriber = { git = "https://github.com/tokio-rs/tracing" }


[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
blake2 = { workspace = true }
bytes = { workspace = true }
ciborium = { workspace = true }
clap = { workspace = true }
ctrlc = { workspace = true, features = ["termination"] }
digest = { workspace = true }
dogstatsd = { workspace = true }
futures = { workspace = true }
gcp_auth = { workspace = true }
hashbrown = { workspace = true }
hdrhistogram = { workspace = true }
hex = { workspace = true }
hsmcore = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
jsonwebtoken = { workspace = true }
libc = { workspace = true }
juicebox-sdk = { workspace = true }
juicebox-sdk-core = { workspace = true }
juicebox-sdk-marshalling = { workspace = true }
juicebox-sdk-networking = { workspace = true }
nix = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-http = { workspace = true }
opentelemetry-otlp = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
secrecy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tower = { workspace = true }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }
voprf = { workspace = true }

[dev-dependencies]
async-recursion = { workspace = true }
criterion = { workspace = true }
expect-test = { workspace = true }
hex-literal = { workspace = true }
once_cell = { workspace = true }
rand_core = { workspace = true, features = ["getrandom"] }
rand_chacha = { workspace = true }
sharks = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }

[lib]
doctest = false

[[bench]]
name = "voprf_benchmark"
harness = false

[[bench]]
name = "sharks_benchmark"
harness = false
