[package]
name = "loam-mvp"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
actix-rt = "2.7.0"
bitvec = "1.0.1"
digest = "0.10.6"
futures = "0.3.25"
hmac = "0.12.1"
rand = "0.8.5"
rmp = "0.8.11"
rmp-serde = "1.1.1"
serde = "1.0.152"
sha2 = "0.10.6"
sharks = "0.5.0"
subtle = "2.4.1"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
voprf = "0.4.0"

[dev-dependencies]
criterion = "0.4.0"
hex-literal = "0.3.4"
rand_chacha = "0.3.1"

[[bench]]
name = "voprf_benchmark"
harness = false
