[workspace]
members = ["codegen", "entrust-agent", "entrust-hsm", "hsmcore"]
# This allows the sdk packages to reference their workspace (for dependencies
# and such), rather than this one.
exclude = ["sdk"]

[package]
name = "loam-mvp"
version = "0.0.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace.dependencies]
aes-gcm = { version = "0.10.1", default-features = false, features = [
    "aes",
    "alloc",
] }
async-recursion = "1.0.2"
async-trait = "0.1.64"
bytes = { version = "1.4.0", default-features = false }
ciborium = { version = "0.2.0", default-features = false }
clap = { version = "4.1.6", features = ["derive"] }
criterion = "0.4.0"
ctrlc = "3.2.5"
digest = "0.10.6"
futures = "0.3.25"
hdrhistogram = { version = "7.5.2", default-features = false }
hex-literal = "0.3.4"
hkdf = "0.12.3"
hmac = "0.12.1"
hsmcore = { path = "hsmcore" }
http = "0.2.8"
http-body-util = "0.1.0-rc.2"
hyper = { version = "1.0.0-rc.2", features = ["http1", "http2", "server"] }
libc = { version = "0.2.139", default-features = false }
loam-sdk = { path = "sdk/rust/sdk/client" }
loam-sdk-core = { path = "sdk/rust/sdk/core" }
loam-sdk-networking = { path = "sdk/rust/sdk/networking" }
loam-sdk-noise = { path = "sdk/rust/sdk/noise" }
nix = { version = "0.26.2", default-features = false, features = ["signal"] }
opentelemetry = { version = "0.18.0", features = ["rt-tokio"] }
opentelemetry-http = "0.7.0"
opentelemetry-otlp = "0.11.0"
prost = "0.11.6"
prost-types = "0.11.6"
rand = { version = "0.8.5", default-features = false, features = ["alloc"] }
rand_core = "0.6.4"
rand_chacha = "0.3.1"
rustls = "0.20.8"
rustls-pemfile = "1.0"
reqwest = { version = "0.11.14", default-features = false, features = [
    "rustls-tls",
] }
serde = { version = "1.0.152", default-features = false, features = [
    "alloc",
    "derive",
] }
sha2 = { version = "0.10.6", default-features = false }
signal-hook = "0.3.15"
subtle = { version = "2.4.1", default-features = false }
tokio = { version = "1.25.0", features = ["rt-multi-thread", "macros"] }
tokio-rustls = "0.23.4"
tonic = { version = "0.8.3", features = [ "channel", "tls", "tls-webpki-roots" ] }
tracing = { version = "0.2.0", default-features = false, features = [
    "alloc",
    "attributes",
] }
# The latest Cargo.toml of tracing-opentelemetry in Git has an old version number.
tracing-opentelemetry = { version = "*" }
# The latest Cargo.toml of tracing-subscriber in Git has an old version number.
tracing-subscriber = { version = "*" }
url = { version = "2.3.1", features = ["serde"] }
voprf = { version = "0.4.0" }
x25519-dalek = { version = "2.0.0-pre.1", default-features = false, features = [
    "reusable_secrets",
    "serde",
    "u64_backend",      # TODO: need 32-bit on HSMs
] }


[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
ctrlc = { workspace = true, features = ["termination"] }
digest = { workspace = true }
futures = { workspace = true }
hdrhistogram = { workspace = true }
hmac = { workspace = true }
hsmcore = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
libc = { workspace = true }
loam-sdk = { workspace = true }
loam-sdk-core = { workspace = true }
loam-sdk-networking = { workspace = true }
nix = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-http = { workspace = true }
opentelemetry-otlp = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
signal-hook = { workspace = true }
tokio = { workspace = true }
tokio-rustls = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }
voprf = { workspace = true }
x25519-dalek = { workspace = true }


[patch.crates-io]
# We need https://github.com/tokio-rs/tracing/pull/2335 to quiet down error return
# values in tokio::instrument, which is not yet unreleased.
tracing = { git = "https://github.com/tokio-rs/tracing" }
tracing-opentelemetry = { git = "https://github.com/tokio-rs/tracing" }
tracing-subscriber = { git = "https://github.com/tokio-rs/tracing" }

[dev-dependencies]
async-recursion = { workspace = true }
criterion = { workspace = true }
hex-literal = { workspace = true }
rand_chacha = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }

[lib]
doctest = false

[[bench]]
name = "voprf_benchmark"
harness = false
