[package]
name = "service_checker"
edition = "2021"
rust-version.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
dogstatsd = { workspace = true }
futures = { workspace = true }
juicebox_sdk = { workspace = true }
juicebox_networking = { workspace = true }
juicebox_realm_auth = { workspace = true }
observability = { workspace = true }
opentelemetry = { workspace = true }
reqwest = { workspace = true }
secret_manager = { workspace = true }
service_core = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
expect-test = { workspace = true }
