[package]
name = "store"
edition = "2021"
version = { workspace = true }
rust-version = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agent_api = { workspace = true }
async_util = { workspace = true }
bigtable = { workspace = true }
bitvec = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
google = { workspace = true }
hex = { workspace = true }
hsm_api = { workspace = true }
http = { workspace = true }
jburl = { workspace = true }
juicebox_marshalling = { workspace = true }
juicebox_realm_api = { workspace = true }
lru-cache = { workspace = true }
observability = { workspace = true }
prost-types = { workspace = true }
rand_core = { workspace = true, features = ["getrandom"] }
retry_loop = { workspace = true }
service_core = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
agent_core = { workspace = true }
hsm_core = { workspace = true, features = ["dot"] }
juicebox_process_group = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
