[package]
name = "store"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agent_api = { workspace = true }
async-trait = { workspace = true }
bitvec = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
gcp_auth = { workspace = true }
google = { workspace = true }
hsm_api = { workspace = true }
http = { workspace = true }
juicebox_api = { workspace = true }
juicebox_marshalling = { workspace = true }
lru-cache = { workspace = true }
observability = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
hsm_core = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
rand_core = { workspace = true, features = ["getrandom"] }
reqwest = { workspace = true }
juicebox_process_group = { workspace = true }
agent_core = { workspace = true }
