[package]
name = "entrust_hsm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
entrust_api = { path = "../entrust_api" }
hashbrown = { workspace = true }
hsmcore = { path = "../hsmcore" }
juicebox-sdk-marshalling = { workspace = true }
rand_core = { workspace = true }
x25519-dalek = { workspace = true }

[lib]
crate-type = ["staticlib"]

[features]
# enables insecure features such as metrics
insecure = []
