[package]
name = "testing"
edition = "2021"
version  = { workspace = true }
rust-version = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agent_api = { workspace = true }
clap = { workspace = true }
cluster_core = { workspace = true }
futures = { workspace = true }
google = { workspace = true }
hex = { workspace = true }
hsm_api = { workspace = true }
hsm_core = { workspace = true, features = ["dot"] }
http = { workspace = true }
itertools = { workspace = true }
juicebox_sdk = { workspace = true }
juicebox_networking = { workspace = true }
juicebox_process_group = { workspace = true }
juicebox_realm_api = { workspace = true }
juicebox_realm_auth = { workspace = true }
observability = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
rand_core = { workspace = true }
reqwest = { workspace = true }
secret_manager = { workspace = true }
serde_json = { workspace = true }
service_core = { workspace = true }
store = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
agent_core = { workspace = true }
anyhow = { workspace = true }
bigtable = { workspace = true }
bitvec = { workspace = true }
chrono = { workspace = true }
cluster_api = { workspace = true }
cluster_core = { workspace = true }
digest = { workspace = true }
juicebox_marshalling = { workspace = true }
juicebox_noise = { workspace = true }
nix = { workspace = true }
rand = { workspace = true }
sysinfo = { workspace = true }
tokio-rustls = { workspace = true }
tonic = { workspace = true }
x25519-dalek = { workspace = true }
