[package]
name = "testing"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agent_api = { workspace = true }
clap = { workspace = true }
cluster_core = { workspace = true }
ctrlc = { workspace = true }
futures = { workspace = true }
google = { workspace = true }
hex = { workspace = true }
hsm_api = { workspace = true }
hsm_core = { workspace = true, features = ["dot"] }
http = { workspace = true }
itertools = { workspace = true }
juicebox_sdk = { workspace = true }
juicebox_networking = { workspace = true }
juicebox_process_group = { workspace = true }
juicebox_realm_api = { workspace = true }
juicebox_realm_auth = { workspace = true }
observability = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
rand_core = { workspace = true }
reqwest = { workspace = true }
secret_manager = { workspace = true }
serde_json = { workspace = true }
store = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
agent_core = { workspace = true }
anyhow = { workspace = true }
bitvec = { workspace = true }
cluster_api = { workspace = true }
cluster_core = { workspace = true }
criterion = { workspace = true }
digest = { workspace = true }
hex-literal = { workspace = true }
juicebox_marshalling = { workspace = true }
juicebox_noise = { workspace = true }
nix = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
sharks = { workspace = true }
sysinfo = { workspace = true }
tokio-rustls = { workspace = true }
voprf = { workspace = true }
x25519-dalek = { workspace = true }

[[bench]]
name = "voprf_benchmark"
harness = false

[[bench]]
name = "sharks_benchmark"
harness = false
