[package]
name = "testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agent_api = { workspace = true }
agent_core = { workspace = true }
clap = { workspace = true }
cluster_api = { workspace = true }
cluster_core = { workspace = true }
ctrlc = { workspace = true }
futures = { workspace = true }
google = { workspace = true }
hex = { workspace = true }
hsmcore = { workspace = true }
http = { workspace = true }
juicebox-sdk = { workspace = true }
juicebox-sdk-core = { workspace = true }
juicebox-sdk-networking = { workspace = true }
juicebox-sdk-process-group = { workspace = true }
juicebox-sdk-realm-auth = { workspace = true }
observability = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
rand_core = { workspace = true }
reqwest = { workspace = true }
secret_manager = { workspace = true }
serde_json = { workspace = true }
store = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
digest = { workspace = true }
hex-literal = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
sharks = { workspace = true }
voprf = { workspace = true }

[[bench]]
name = "voprf_benchmark"
harness = false

[[bench]]
name = "sharks_benchmark"
harness = false
