[package]
name = "software_hsm"
edition = "2021"
version = { workspace = true }
rust-version = { workspace = true }
build = "../build_info/build_script.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
blake2 = { workspace = true }
build_info = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
hex = { workspace = true, features=["std"] }
hkdf = { workspace = true }
hsm_api = { workspace = true }
hsm_core = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
jburl = { workspace = true }
observability = { workspace = true }
rand = { workspace = true }
service_core = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
x25519-dalek = { workspace = true }

[dev-dependencies]
expect-test = { workspace = true }
