[package]
name = "service_core"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
juicebox_marshalling = { workspace = true }
juicebox_networking = { workspace = true }
observability = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
