[package]
name = "software_hsm_client"
edition = "2021"
rust-version.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agent_core = { workspace = true }
async-trait = { workspace = true }
http = { workspace = true }
juicebox_marshalling = { workspace = true }
opentelemetry = { workspace = true }
reqwest = { workspace = true }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
url = { workspace = true }
