[package]
name = "bitvec"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
juicebox-sdk-marshalling = { workspace = true }
serde = { workspace = true }
