#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

// bindings.rs is generated by build.rs
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
