[package]
name = "merkle_tree_docgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hsmcore = { workspace = true, features = [ "dot" ] }
juicebox-sdk-core = { workspace = true }
tokio = { workspace = true }
