[target.powerpc-unknown-linux-gnu]
rustflags=["-Ctarget-cpu=e5500"]
linker = "powerpc-linux-gnu-gcc-9"

# linking options for the host side seelib (entrust)
[target.x86_64-unknown-linux-gnu.seelib]
rustc-link-search=["/opt/nfast/c/csd/gcc/lib/"]
rustc-link-lib=["rqcard","nfkm","nfstub","nflog","cutils","rqcard","nfkm","nfstub","nflog","cutils"]
