[package]
name = "cluster_bench"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
dogstatsd = { workspace = true }
futures = { workspace = true }
hdrhistogram = { workspace = true }
google = { path = "../google" }
juicebox_hsm = { path = ".." }
juicebox-sdk = { workspace = true }
juicebox-sdk-networking = { workspace = true }
juicebox-sdk-process-group = { workspace = true }
juicebox-sdk-realm-auth = { workspace = true }
observability = { path = "../observability" }
reqwest = { workspace = true }
secret_manager = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
