[package]
name = "entrust_api"
version = "0.2.0"
edition = "2021"
rust-version = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
juicebox_marshalling = { workspace = true }
serde = { workspace = true }
