[package]
name = "software_agent"
edition = "2021"
version  = { workspace = true }
rust-version = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agent_core = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
observability = { workspace = true }
service_core = { workspace = true }
software_hsm_client = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
expect-test = { workspace = true }
