[package]
name = "software_agent"
edition = "2021"
version = { workspace = true }
rust-version = { workspace = true }
build = "../build_info/build_script.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agent_core = { workspace = true }
build_info = { workspace = true }
clap = { workspace = true }
jburl = { workspace = true }
nix = { workspace = true }
observability = { workspace = true }
service_core = { workspace = true }
software_hsm_client = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
expect-test = { workspace = true }
