[package]
name = "software_agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agent_core = { path = "../agent_core" }
anyhow = { workspace = true }
async-trait = { workspace = true }
blake2 = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
ctrlc = { workspace = true, features = ["termination"] }
futures = { workspace = true }
google = { path = "../google" }
hex = { workspace = true }
hkdf = { workspace = true }
hmac = { workspace = true }
hsmcore = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
juicebox-sdk-marshalling = { workspace = true }
observability = { path = "../observability" }
rand = { workspace = true }
reqwest = { workspace = true }
service_core = { workspace = true }
store = { path = "../store" }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
x25519-dalek = { workspace = true }

[dev-dependencies]
expect-test = { workspace = true }
