[package]
name = "software_agent"
edition = "2021"
version  = { workspace = true }
rust-version = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agent_core = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
blake2 = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
google = { workspace = true }
google_pubsub = { workspace = true }
hex = { workspace = true }
hkdf = { workspace = true }
hmac = { workspace = true }
hsm_api = { workspace = true }
hsm_core = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
juicebox_marshalling = { workspace = true }
observability = { workspace = true }
pubsub_api = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
x25519-dalek = { workspace = true }

[dev-dependencies]
expect-test = { workspace = true }
