[package]
name = "secret_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
gcp_auth = { workspace = true }
google = { path = "../google" }
http = { workspace = true }
juicebox-sdk-core = { workspace = true }
juicebox-sdk-realm-auth = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
